### ISSUE TITLE
Not Working - Won't Save/Edit Tags

### ISSUE THREAD

**Issue by DoctorToBeIn23** [ijgnd/anki__extended_tag_edit_add_dialog#12]
All Versions from ⁨2.1.56 through 2.1.62 
Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
MacBook Pro
13-inch, M1, 2020
macOS Ventura Version 13.2.1

When adding a new tag or editing an existing one in the dialogue box it does not save the tag.

**Comment by ijgnd** [comment]
Thanks for the report.

Could you describe the exact to reproduce the problem. The way I usually use the add-on I can't reproduce the problem, see this screencast made with 2.1.61qt6 with only the exteneded tag addon installed (with the default config). I used the shortcut Ctrl+t, d

see: https://github.com/ijgnd/temp/blob/main/61_extended_tag_no_error.mkv?raw=true

&nbsp;

I forgot to upload one change for 2.1.50 or newer. In these versions the option `"editor: show filterdialog to add single tag": "Ctrl+t, a"` simply had no effect.  But this should be a different problem. 

Could you try again with the following newer version and report if it works and if it affects the problem you reported: https://github.com/ijgnd/anki__extended_tag_edit_add_dialog/releases/download/2023-04-a/anki__extended_tag_edit_add_dialog__2023-03-25___only_for_50+.ankiaddon

**Comment by ijgnd** [comment]
@DoctorToBeIn23 just wanted to bring this back to your mind if this slipped your mind. If you are busy at the moment, no problem.

**Comment by DoctorToBeIn23** [comment]
Hey sorry I am back. I am still having issues with this I am now testing 2.1.64Qt6. I have noticed its when there are a bunch of tags on the same note. I will try and add a new tag on an empty line with no effect. Also if I try and replace a tag it won't work. It does work with fewer tags on the cards.

**Comment by DoctorToBeIn23** [comment]
![Jun-01-2023 13-44-21](https://github.com/ijgnd/anki__extended_tag_edit_add_dialog/assets/60248099/11d84a56-336a-4b04-847c-f6556f94c961)

**Comment by ijgnd** [comment]
thanks for sharing this. 

your screencast really helped.

I can reproduce the problem.

At the moment I suspect that it occurs only under the folloing circumstances:it's the following:
- you edit a note with many tags so that you use the new dialog I introduced in March 2022 (to solve [the problem you reported here](https://forums.ankiweb.net/t/extended-tag-add-edit-dialog-official-thread/553/18). The default setting to switch to this new type of dialog is having 12 tags iirc
- further condition:
    - This problem does not happen it you use the mouse to close my  tag window
    - this problem does not happen if after deleting or changing or adding a tag you put the cursor into a different line
    - this problem only occurs if you use the **shortcut to close the window while the focus/cursor is still on the line you modified.**

Can you confirm that the bug only occurs under these circumstances? 

If you can confirm this, try this: 

-------

Open the add-on folder in your addons21 folder. You can do this from the anki add-on dialog. Select my add-on then click the "View Files" button. You might have to navigate to my add-on folder based on the ankiweb addon id which is 1135507717

Inside this folder there's a file named 'tag_dialog_extended__QListWidgetFromDesigner.py'. Open this file in a text editor like VSCode  or Apple's TextEdit (in plain text mode) ...

Then change the [Line 197](https://github.com/ijgnd/anki__extended_tag_edit_add_dialog/blob/16e0cf7c6c073fe555d77906569135e93e240b7f/src/tag_dialog_extended__QListWidgetFromDesigner.py#L197) from this:

    def accept(self):
        self.tagstring = ""

to

    def accept(self):
        current_row = self.form.listWidget.currentRow()
        focus_helper = 0 if current_row != 0 else 1
        self.form.listWidget.setCurrentRow(focus_helper)
        self.tagstring = ""

make sure to keep the indentation level the same with 8 spaces before each new line.

Then save this file and restart Anki. 

Does the problem persist?

This is not a good solution but these lines I made for diagnosing the problem also seem to solve it for me.

**Comment by DoctorToBeIn23** [comment]
Yes you were correct on everything and I did change the code which solved my issue are you going to push this for everyone? I work for the AnKing team and focus on trying to keep and notify everyone of bugs and on behalf of the team we would appreciate it because so many of the notes in the deck have well over 12 tags per card.

**Comment by ijgnd** [comment]
I just uploaded this new version. Check for updates and you should get it. If you still run into this problem or another one please let me know and reopen this (or another) issue.

Once more thanks for reporting this serious bug. I didn't notice it because my notes have much fewer tags.

**Comment by ijgnd** [comment]
@DoctorToBeIn23 : I have an off-topic request. If you use the following add-ons could you test these new versions and let me know if you run into problems with them. Just install them and use them regularly for a week or so. 

- [BetterSearch](https://ankiweb.net/shared/info/1052724801):
    - The new version has some changes under the hood, which might have introduced bugs by accident that you might find by regularly using it.
    - the default shortcuts have chagned from Ctrl+ to Alt+ so that the editor shortcuts for Latex in 2.1.50+ no longer break and that there's no conflict with the MacOS Cmd+H for hiding windows. I don't have a Mac, hopefully Alt+... works?
    - in the browser all functions of this add-on are moved from the view menu into a separate menu named "BetterSearch"
    - the included part about search from the manual (so that you have the manual even if you are offline) can now be searched with ctrl+f. Also this view adopts to day/night mode changes
    - in the multi-line window to edit search terms you can now use shortcuts (the same ones as in the browser, e.g.  "Alt+H, f" for the "field from note dialog"
    - when inserting tags they are now surround with "". Two people asked for this. I see no downside. Should I keep this change?

- [add-on dialog search/filter bar](https://ankiweb.net/shared/info/561945101). 
    - The new version should fix two problems: Now the "View Add-on Page" button should open the correct add-on and now the "Config" button should not wrongly be greyed out. My code changes could have introduced bugs that e.g. now the "Config" button under some conditions opens the config of a wrong add-on when you click it.

On github you can't attach .ankiaddon files. So I renamed the files by adding the extension ".zip". After downloading the two files and before adding them to anki just rename them in the Finder/Explorer and remove ".zip"

Thanks.

[anki__add-on_window_search_filter_bar__2023-06-11.zip](https://github.com/ijgnd/anki__extended_tag_edit_add_dialog/files/11721694/anki__add-on_window_search_filter_bar__2023-06-11.zip)
[anki__browser_search__quick_insert_tag_deck_notetype__BetterSearch__2023-06-12_22-16.ankiaddon.zip](https://github.com/ijgnd/anki__extended_tag_edit_add_dialog/files/11728020/anki__browser_search__quick_insert_tag_deck_notetype__BetterSearch__2023-06-12_22-16.ankiaddon.zip)

**Comment by DoctorToBeIn23** [comment]
Where is the new uworld add on code? I tried to download it from here but it doesn't show up when I manually put it in the add on folder.
https://github.com/AnKing-VIP/uworld_qid_to_anki_search

I will test those other two today.
